### ISSUE TITLE
Index Out of bound 

### ISSUE THREAD

**Issue by hardikdevios** [bluesnap/bluesnap-android-int#10]
**- Application is Crashing during Creditcard entry** 
Here is the Log 
> Exception in MessageQueue callback: handleReceiveCallback
> MessageQueue-JNI: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
>         at java.util.ArrayList.get(ArrayList.java:437)
>         at android.widget.TextView.sendOnTextChanged(TextView.java:10535)
>         at android.widget.TextView.handleTextChanged(TextView.java:10625)
>         at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:13375)
>         at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1267)
>         at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
>         at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
>         at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
>         at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
>         at android.widget.TextView.doKeyDown(TextView.java:8430)
>         at android.widget.TextView.onKeyDown(TextView.java:8187)
>         at android.view.KeyEvent.dispatch(KeyEvent.java:2801)
>         at android.view.View.dispatchKeyEvent(View.java:13352)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
>         at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
>         at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1839)
>         at android.app.Activity.dispatchKeyEvent(Activity.java:3953)
>         at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:108)
>         at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
>         at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
>         at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
>         at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
>         at 

Let me know if you need more information 
Version: 2.3.3
Android Studio: 3.5
Android OS: API 29(Android 10)

**Comment by hardikdevios** [comment]
Any update for me ?

**Comment by snpori** [comment]
Hi. This will be pushed up in our priority.
Can you provide steps to reproduce? this will be helpful.

**Comment by hardikdevios** [comment]
@snpori Simple Checkout UI 
Start typing credit card entry and when you reach the end of the Card number it will crash.

**Comment by hardikdevios** [comment]
@snpori Let me know if you need any more information to reproduce this issue.

**Comment by hardikdevios** [comment]
@snpori Attaching video for further investigation. Also, I have mailed you.


[device-2019-11-19-161115.mp4.zip](https://github.com/bluesnap/bluesnap-android-int/files/3863461/device-2019-11-19-161115.mp4.zip)

**Comment by hardikdevios** [comment]
@snpori 

Hello,

We have created Demo Application and this time error is different it's not even opening the BlueSnapCheckoutActivity.
Just to update you we are working on the AndroidX support compiler, we have attached the demo here. Can you please help us with that?

Android X Link: https://developer.android.com/jetpack/androidx/migrate

Demo Project Link: https://drive.google.com/open?id=1BMtv8dSV6EsDXEiAnCS85wAI5UzRLpwu

**Comment by hardikdevios** [comment]
@snpori  Any update on this?

**Comment by hardikdevios** [comment]
@snpori Guys Please respond to us on the status of this issue, This is not helping us anymore we are kept waiting for this, If you guys still need more help we are ready to corporate. Please update us with anything like you guys are investigating or you found that and working on fixes.
