### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException BluesnapCheckoutActivity

### ISSUE THREAD

**Issue by yar-ok** [bluesnap/bluesnap-android-int#6]
BluesnapCheckoutActivity crashes on launch.

BluesnapCheckoutActivity.java line 66
com.bluesnap.androidapi.BluesnapCheckoutActivity.onCreate

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{..................../com.bluesnap.androidapi.BluesnapCheckoutActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment

Full stack 
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{......................../com.bluesnap.androidapi.BluesnapCheckoutActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment

Caused by android.view.InflateException: Binary XML file line #0: Error inflating class fragment

Caused by java.lang.IllegalStateException: Fragment com.bluesnap.androidapi.views.BluesnapFragment did not create a view.
       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2348)
       at android.app.FragmentController.onCreateView(FragmentController.java:98)
       at android.app.Activity.onCreateView(Activity.java:6126)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:454)
       at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:290)
       at android.app.Activity.setContentView(Activity.java:2515)
       at com.bluesnap.androidapi.BluesnapCheckoutActivity.onCreate(BluesnapCheckoutActivity.java:66)
       at android.app.Activity.performCreate(Activity.java:6910)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`
![screen shot 2018-01-12 at 10 46 07 am](https://user-images.githubusercontent.com/4439595/34866772-5ec97690-f786-11e7-8914-2dd462e55c98.png)

**Comment by yar-ok** [comment]
Researched and found info that this crash can be because of this implementation:
```
  <fragment
            android:id="@+id/fraglyout"
            android:name="com.bluesnap.androidapi.views.BluesnapFragment"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            tools:layout="@layout/bluesnap_checkout_creditcard" />
```
From bluesnap_default_ui.xml

https://stackoverflow.com/questions/19874882/android-view-inflateexception-binary-xml-file-error-inflating-class-fragment/35436245

**Comment by RYBR** [comment]
thank you for your input, we will look into that...
was this a one time occurrence or a repeating one?
what is the phone and phone model you used? (was it an emulator?)

**Comment by RYBR** [comment]
Also, what is the BlueSnap SDK version you use?
and what android support library version do you use?

**Comment by olenev** [comment]
I cannot reproduce on own or available devices. It happens on user's devices. 
All issues are on real phones, like Huawei VTR-L29, P925;  Samsung Galaxy S6; OPPO CPH1607;
Sony Xperia Z3+; 
Use import com.bluesnap:bluesnap-android:1.0.13 and supports 25.4.0.

**Comment by yar-ok** [comment]
I cannot reproduce on own or available devices. It happens on user's devices.
All issues are on real phones, like Huawei VTR-L29, P925; Samsung Galaxy S6; OPPO CPH1607;
Sony Xperia Z3+;
Use import com.bluesnap:bluesnap-android:1.0.13 and supports 25.4.0.

**Comment by snpori** [comment]
Thanks for the heads up. we also find it hard to reproduce this issue however there are changes in the fragment population in version 1.0.14 and 1.1.0 so it seems that newer version are not affected by this. also there are some changes in our pipeline that affect the layout and the use of fragments and may address this as well.
